apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rustfs.fullname" . }}-secret
type: Opaque
data:
  RUSTFS_ACCESS_KEY: {{ .Values.secret.rustfs.access_key | b64enc | quote }}
  RUSTFS_SECRET_KEY: {{ .Values.secret.rustfs.secret_key | b64enc | quote }}

